name: Pages
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
        with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
         fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
 
      - name: make the sphinx docs
        run: |
              make -C docs clean
              sphinx-apidoc -f -o . ..
              # make -C docs html
              
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
