name: Pages
on:
   push:
      branches:
         - main
permissions:
   contents: write
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
           with:
              persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
              fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

         - name: Setup Python
           uses: actions/setup-python@v4.3.0
           with:
              python-version: 3.10.1

         - name: Install dependencies
           run: |
              python -m pip install -U sphinx
              python -m pip install sphinx-rtd-theme
              python -m pip install sphinxcontrib-apidoc
              python -m pip install sphinx-autodoc-typehints

         - name: make the sphinx docs
           run: |
              make -C docs clean 
              sphinx-apidoc -f -o . ..
              make -C docs html

         - uses: ammaraskar/sphinx-action@0.4
           with:
              docs-folder: "docs/"

         - name: Push changes
           uses: ad-m/github-push-action@v0.6.0
           with:
              branch: gh-pages
              github_token: ${{ secrets.GITHUB_TOKEN }}
         - name: archive
           uses: actions/upload-pages-artifact@v0
           with:
              path: .
              retention-days: 1

   deploy:
      # Add a dependency to the build job
      needs: build

      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
         pages: write # to deploy to Pages
         id-token: write # to verify the deployment originates from an appropriate source

      # Deploy to the github-pages environment
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}

      # Specify runner + deployment step
      runs-on: ubuntu-latest
      steps:
         - name: Deploy to GitHub Pages
           id: deployment
           uses: actions/deploy-pages@v1
